---
- name: Prepare
  hosts: all
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install git package
      package:
        name: git
        state: present
